### ISSUE TITLE
住所の正規化エラー

### ISSUE THREAD

**Issue by miya0001** [geolonia/normalize-japanese-addresses#59]
#58 で追加したテストで発生するエラー

```
  ● 千葉県鎌ケ谷市中佐津間２丁目１５－１４－９

    Can't detect the city.

       95 | 
       96 |   if (!city) {
    >  97 |     throw new Error("Can't detect the city.")
          |           ^
       98 |   }
       99 | 
      100 |   // 町丁目以降の正規化

      at src/main.ts:97:11
      at step (src/main.ts:33:23)
      at Object.next (src/main.ts:14:53)
      at fulfilled (src/main.ts:5:58)

  ● 千葉県鎌ケ谷市東鎌ケ谷３丁目２６－１６

    Can't detect the city.

       95 | 
       96 |   if (!city) {
    >  97 |     throw new Error("Can't detect the city.")
          |           ^
       98 |   }
       99 | 
      100 |   // 町丁目以降の正規化

      at src/main.ts:97:11
      at step (src/main.ts:33:23)
      at Object.next (src/main.ts:14:53)
      at fulfilled (src/main.ts:5:58)

  ● 千葉県鎌ケ谷市道野辺本町１丁目３－１

    Can't detect the city.

       95 | 
       96 |   if (!city) {
    >  97 |     throw new Error("Can't detect the city.")
          |           ^
       98 |   }
       99 | 
      100 |   // 町丁目以降の正規化

      at src/main.ts:97:11
      at step (src/main.ts:33:23)
      at Object.next (src/main.ts:14:53)
      at fulfilled (src/main.ts:5:58)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 6211 passed, 6214 total
Snapshots:   0 total
Time:        256.184 s, estimated 286 s
```

**Comment by miya0001** [comment]
#51 と同じ問題だった。

**Comment by miya0001** [comment]
https://github.com/geolonia/normalize-japanese-addresses/pull/58 で解決したので閉じる
