### ISSUE TITLE
buildings.csv の中で町名を認識できなかった住所

### ISSUE THREAD

**Issue by miya0001** [geolonia/normalize-japanese-addresses#60]
以下のリストの中で町名を認識できなかった住所のリスト。
（都道府県名及び市区町村名は認識できていた）
https://github.com/geolonia/normalize-japanese-addresses/blob/master/test/buildings.csv

```
  ● 神奈川県横浜市緑区中山５丁目１－２４

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      16 |     expect(!! res.pref).toStrictEqual(true)
      17 |     expect(!! res.city).toStrictEqual(true)
    > 18 |     expect(!! res.town).toStrictEqual(true)
         |                         ^
      19 |     expect(!! res.addr).toStrictEqual(true)
      20 |   })
      21 | }

      at test/buildings.test.ts:18:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

  ● 千葉県流山市東初石６丁目１８５－６

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      16 |     expect(!! res.pref).toStrictEqual(true)
      17 |     expect(!! res.city).toStrictEqual(true)
    > 18 |     expect(!! res.town).toStrictEqual(true)
         |                         ^
      19 |     expect(!! res.addr).toStrictEqual(true)
      20 |   })
      21 | }

      at test/buildings.test.ts:18:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

  ● 千葉県流山市十太夫２１２

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      16 |     expect(!! res.pref).toStrictEqual(true)
      17 |     expect(!! res.city).toStrictEqual(true)
    > 18 |     expect(!! res.town).toStrictEqual(true)
         |                         ^
      19 |     expect(!! res.addr).toStrictEqual(true)
      20 |   })
      21 | }

      at test/buildings.test.ts:18:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

  ● 大阪府四條畷市中野３２－５

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      16 |     expect(!! res.pref).toStrictEqual(true)
      17 |     expect(!! res.city).toStrictEqual(true)
    > 18 |     expect(!! res.town).toStrictEqual(true)
         |                         ^
      19 |     expect(!! res.addr).toStrictEqual(true)
      20 |   })
      21 | }

      at test/buildings.test.ts:18:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 6210 passed, 6214 total
Snapshots:   0 total
Time:        308.701 s, estimated 309 s
```

**Comment by miya0001** [comment]
`神奈川県横浜市緑区中山５丁目１－２４` は令和元年にできたからか、位置参照情報のデータにも地名がなかった。
https://www.city.yokohama.lg.jp/kurashi/koseki-zei-hoken/todokede/jukyo/kako/jisshi-r1.html

**Comment by miya0001** [comment]
`千葉県流山市東初石６丁目１８５－６` は、うちの現在の API にはないが、位置参照情報の街区レベルにはあるので、https://github.com/geolonia/japanese-addresses/issues/17 で解消すると思われる。

**Comment by miya0001** [comment]
`千葉県流山市十太夫２１２` も現在のうちのAPIにはないが、位置参照情報の街区レベルにはあるので、geolonia/japanese-addresses#17 で解消すると思われる。

**Comment by miya0001** [comment]
`大阪府四條畷市中野３２－５` は、住居表示を整備する前の地番住所っぽい。

**Comment by miya0001** [comment]
精度があがったせいか今まで出ていなかったエラーがでるようになった。

```
● 神奈川県横浜市緑区中山５丁目１－２４

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      16 |     expect(!! res.pref).toStrictEqual(true)
      17 |     expect(!! res.city).toStrictEqual(true)
    > 18 |     expect(!! res.town).toStrictEqual(true)
         |                         ^
      19 |     expect(!! res.addr).toStrictEqual(true)
      20 |   })
      21 | }

      at test/buildings.test.ts:18:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

  ● 神奈川県川崎市宮前区西野川１丁目４０－２８

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      16 |     expect(!! res.pref).toStrictEqual(true)
      17 |     expect(!! res.city).toStrictEqual(true)
    > 18 |     expect(!! res.town).toStrictEqual(true)
         |                         ^
      19 |     expect(!! res.addr).toStrictEqual(true)
      20 |   })
      21 | }

      at test/buildings.test.ts:18:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

  ● 千葉県流山市東初石６丁目１８５－６

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      16 |     expect(!! res.pref).toStrictEqual(true)
      17 |     expect(!! res.city).toStrictEqual(true)
    > 18 |     expect(!! res.town).toStrictEqual(true)
         |                         ^
      19 |     expect(!! res.addr).toStrictEqual(true)
      20 |   })
      21 | }

      at test/buildings.test.ts:18:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

  ● 神奈川県川崎市宮前区南野川２丁目６２－２４

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      16 |     expect(!! res.pref).toStrictEqual(true)
      17 |     expect(!! res.city).toStrictEqual(true)
    > 18 |     expect(!! res.town).toStrictEqual(true)
         |                         ^
      19 |     expect(!! res.addr).toStrictEqual(true)
      20 |   })
      21 | }

      at test/buildings.test.ts:18:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

  ● 千葉県流山市十太夫２１２

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      16 |     expect(!! res.pref).toStrictEqual(true)
      17 |     expect(!! res.city).toStrictEqual(true)
    > 18 |     expect(!! res.town).toStrictEqual(true)
         |                         ^
      19 |     expect(!! res.addr).toStrictEqual(true)
      20 |   })
      21 | }

      at test/buildings.test.ts:18:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

  ● 大阪府四條畷市中野３２－５

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      16 |     expect(!! res.pref).toStrictEqual(true)
      17 |     expect(!! res.city).toStrictEqual(true)
    > 18 |     expect(!! res.town).toStrictEqual(true)
         |                         ^
      19 |     expect(!! res.addr).toStrictEqual(true)
      20 |   })
      21 | }

      at test/buildings.test.ts:18:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

  ● 神奈川県川崎市宮前区西野川２丁目２９－４６

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      16 |     expect(!! res.pref).toStrictEqual(true)
      17 |     expect(!! res.city).toStrictEqual(true)
    > 18 |     expect(!! res.town).toStrictEqual(true)
         |                         ^
      19 |     expect(!! res.addr).toStrictEqual(true)
      20 |   })
      21 | }

      at test/buildings.test.ts:18:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

Test Suites: 1 failed, 1 total
Tests:       7 failed, 6207 passed, 6214 total
Snapshots:   0 total
Time:        305.502 s
```

**Comment by miya0001** [comment]
#73 に続く。
