### ISSUE TITLE
正規化ができなかった住所のリスト

### ISSUE THREAD

**Issue by miya0001** [geolonia/normalize-japanese-addresses#73]
● 東京都新宿区三栄町２－８

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      16 |     expect(!! res.pref).toStrictEqual(true)
      17 |     expect(!! res.city).toStrictEqual(true)
    > 18 |     expect(!! res.town).toStrictEqual(true)
         |                         ^
      19 |     expect(!! res.addr).toStrictEqual(true)
      20 |   })
      21 | }

      at test/buildings.test.ts:18:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

  ● 神奈川県横浜市泉区和泉町６２１２－３

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      16 |     expect(!! res.pref).toStrictEqual(true)
      17 |     expect(!! res.city).toStrictEqual(true)
    > 18 |     expect(!! res.town).toStrictEqual(true)
         |                         ^
      19 |     expect(!! res.addr).toStrictEqual(true)
      20 |   })
      21 | }

      at test/buildings.test.ts:18:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

  ● 東京都新宿区三栄町１７－１６

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      16 |     expect(!! res.pref).toStrictEqual(true)
      17 |     expect(!! res.city).toStrictEqual(true)
    > 18 |     expect(!! res.town).toStrictEqual(true)
         |                         ^
      19 |     expect(!! res.addr).toStrictEqual(true)
      20 |   })
      21 | }

      at test/buildings.test.ts:18:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

  ● 埼玉県新座市新堀２丁目

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      17 |     expect(!! res.city).toStrictEqual(true)
      18 |     expect(!! res.town).toStrictEqual(true)
    > 19 |     expect(!! res.addr).toStrictEqual(true)
         |                         ^
      20 |   })
      21 | }
      22 | 

      at test/buildings.test.ts:19:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 1031 passed, 1035 total
Snapshots:   0 total
Time:        53.014 s, estimated 305 s

**Comment by miya0001** [comment]
住所APIがキャッシュだったみたいで、新データで試したら以下の3件だった。

```
  ● 東京都新宿区三栄町２－８

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      16 |     expect(!! res.pref).toStrictEqual(true)
      17 |     expect(!! res.city).toStrictEqual(true)
    > 18 |     expect(!! res.town).toStrictEqual(true)
         |                         ^
      19 |     expect(!! res.addr).toStrictEqual(true)
      20 |   })
      21 | }

      at test/buildings.test.ts:18:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

  ● 東京都新宿区三栄町１７－１６

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      16 |     expect(!! res.pref).toStrictEqual(true)
      17 |     expect(!! res.city).toStrictEqual(true)
    > 18 |     expect(!! res.town).toStrictEqual(true)
         |                         ^
      19 |     expect(!! res.addr).toStrictEqual(true)
      20 |   })
      21 | }

      at test/buildings.test.ts:18:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

  ● 埼玉県新座市新堀２丁目

    expect(received).toStrictEqual(expected) // deep equality

    Expected: true
    Received: false

      17 |     expect(!! res.city).toStrictEqual(true)
      18 |     expect(!! res.town).toStrictEqual(true)
    > 19 |     expect(!! res.addr).toStrictEqual(true)
         |                         ^
      20 |   })
      21 | }
      22 | 

      at test/buildings.test.ts:19:25
      at step (test/buildings.test.ts:33:23)
      at Object.next (test/buildings.test.ts:14:53)
      at fulfilled (test/buildings.test.ts:5:58)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 1032 passed, 1035 total
Snapshots:   0 total
Time:        79.654 s
```

**Comment by miya0001** [comment]
## 東京都新宿区三栄町２－８

住所データでは `東京都新宿区四谷三栄町` になっている。

## 埼玉県新座市新堀２丁目

番地レベルがなく町丁目レベルまでしかない不完全な住所によるエラー。

**Comment by miya0001** [comment]
住所データの方で検討する。
https://github.com/geolonia/japanese-addresses/issues/24
