### ISSUE TITLE
香川県仲多度郡まんのう町勝浦字家六２０９４番地１　漢数字と英数字が連続した住所でエラー

### ISSUE THREAD

**Issue by hirokoma** [geolonia/normalize-japanese-addresses#94]
```
const { normalize } = require('@geolonia/normalize-japanese-addresses')
normalize('香川県仲多度郡まんのう町勝浦字家六２０９４番地１').then(result => {console.log(result)})
```

```
/home/koma/works/address_normalizer/geolonia_server/node_modules/@geolonia/normalize-japanese-addresses/dist/main.js:272
            throw new TypeError('The attribute of kanji2number() must be a Japanese numeral as integer.');
                  ^

TypeError: The attribute of kanji2number() must be a Japanese numeral as integer.
    at Object.kanji2number (/home/koma/works/address_normalizer/geolonia_server/node_modules/@geolonia/normalize-japanese-addresses/dist/main.js:272:19)
    at kan2num (/home/koma/works/address_normalizer/geolonia_server/node_modules/@geolonia/normalize-japanese-addresses/dist/main.js:380:55)
    at /home/koma/works/address_normalizer/geolonia_server/node_modules/@geolonia/normalize-japanese-addresses/dist/main.js:569:32
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at /home/koma/works/address_normalizer/geolonia_server/node_modules/@geolonia/normalize-japanese-addresses/dist/main.js:568:26
    at step (/home/koma/works/address_normalizer/geolonia_server/node_modules/@geolonia/normalize-japanese-addresses/dist/main.js:59:23)
    at Object.next (/home/koma/works/address_normalizer/geolonia_server/node_modules/@geolonia/normalize-japanese-addresses/dist/main.js:40:53)
    at fulfilled (/home/koma/works/address_normalizer/geolonia_server/node_modules/@geolonia/normalize-japanese-addresses/dist/main.js:30:58)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

同様のエラーが起きる別の住所

```
愛知県あま市西今宿梶村一３８番地４
香川県丸亀市原田町字東三分一１９２６番地１
```

**Comment by miya0001** [comment]
@hirokoma ありがとうございます！

**Comment by miya0001** [comment]
以下メモ

* エラーが出てしまうことと正規化が失敗することは別々の問題なので、まずエラーを解消すること。
* 以下 API のレスポンス
  * https://geolonia.github.io/japanese-addresses/api/ja/%E9%A6%99%E5%B7%9D%E7%9C%8C/%E4%BB%B2%E5%A4%9A%E5%BA%A6%E9%83%A1%E3%81%BE%E3%82%93%E3%81%AE%E3%81%86%E7%94%BA.json
  * https://geolonia.github.io/japanese-addresses/api/ja/%E6%84%9B%E7%9F%A5%E7%9C%8C/%E3%81%82%E3%81%BE%E5%B8%82.json
  * https://geolonia.github.io/japanese-addresses/api/ja/%E9%A6%99%E5%B7%9D%E7%9C%8C/%E4%B8%B8%E4%BA%80%E5%B8%82.json
