### ISSUE TITLE
沖縄県那覇市小禄１丁目５番２３号１丁目マンション３０１　建物名に「N丁目」という文字列が含まれているとエラー

### ISSUE THREAD

**Issue by hirokoma** [geolonia/normalize-japanese-addresses#95]
```
const { normalize } = require('@geolonia/normalize-japanese-addresses')
normalize('沖縄県那覇市小禄１丁目５番２３号１丁目マンション３０１').then(result => {console.log(result)})
```

```
/home/koma/works/address_normalizer/geolonia_server/node_modules/@geolonia/normalize-japanese-addresses/dist/main.js:272
            throw new TypeError('The attribute of kanji2number() must be a Japanese numeral as integer.');
                  ^

TypeError: The attribute of kanji2number() must be a Japanese numeral as integer.
    at Object.kanji2number (/home/koma/works/address_normalizer/geolonia_server/node_modules/@geolonia/normalize-japanese-addresses/dist/main.js:272:19)
    at kan2num (/home/koma/works/address_normalizer/geolonia_server/node_modules/@geolonia/normalize-japanese-addresses/dist/main.js:380:55)
    at /home/koma/works/address_normalizer/geolonia_server/node_modules/@geolonia/normalize-japanese-addresses/dist/main.js:572:32
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at /home/koma/works/address_normalizer/geolonia_server/node_modules/@geolonia/normalize-japanese-addresses/dist/main.js:571:26
    at step (/home/koma/works/address_normalizer/geolonia_server/node_modules/@geolonia/normalize-japanese-addresses/dist/main.js:59:23)
    at Object.next (/home/koma/works/address_normalizer/geolonia_server/node_modules/@geolonia/normalize-japanese-addresses/dist/main.js:40:53)
    at fulfilled (/home/koma/works/address_normalizer/geolonia_server/node_modules/@geolonia/normalize-japanese-addresses/dist/main.js:30:58)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

`沖縄県那覇市小禄１丁目５番２３号マンション３０１` であればエラーは発生せず。

**Comment by miya0001** [comment]
@hirokoma ありがとうございます！
